### ISSUE TITLE
Define the pattern of a notebook.

### ISSUE THREAD

**Issue by metaboulie** [Haleshot/marimo-tutorials#5]
Define the design patterns of every notebook, e.g., the structure (custom constants, directory, intro, main, summary, refs, code), the footer (authors, copyrights), styling…
Create a starter notebook to automatic as many repetitive works as possible.

**Comment by Haleshot** [comment]
Having a good banner in addition to READMEs and sidebars (like shown [here](https://marimo.io/@public/signal-decomposition).

**Comment by metaboulie** [comment]
We can remove `mo.sidebar` for our design bacause the `View outline` panel can better show the outline, and we can use banner for additional info, e.g, our github links…

**Comment by metaboulie** [comment]
it would save some time for us to abandon the implementation of sidebar,
a strange idea just came to me that we can illustrate A/B test using this,
i.e., A group with sidebar and B group without sidebar, then when they first open this, `a/b_test.py`, sidebar will be randomly rendered or not, and we gather the user feedback and use these feedbacks to do some analysis inside the same notebook

**Comment by Haleshot** [comment]
> it would save some time for us to abandon the implementation of sidebar, a strange idea just came to me that we can illustrate A/B test using this, i.e., A group with sidebar and B group without sidebar, then when they first open this, `a/b_test.py`, sidebar will be randomly rendered or not, and we gather the user feedback and use these feedbacks to do some analysis inside the same notebook

Makes sense. For me, making a sidebar is easy as I have the markdown content ready (from my repo READMEs); I just need to change the category sections/sidebar names.

What you propose seems interesting... I'm focusing on the existing project issues for now. Trying to convert all my jupyter programs with marimo integrations and methods.

**Comment by Haleshot** [comment]
Should I close this issue as fixed via #21

**Comment by metaboulie** [comment]
thanks
